[libraries]
jetty-bom = { module = "org.eclipse.jetty:jetty-bom" }
jetty-server = { module = "org.eclipse.jetty:jetty-server" }
jetty-servlet = { module = "org.eclipse.jetty:jetty-servlet" }

guava = { module = "com.google.guava:guava" }

httpclient = { module = "org.apache.httpcomponents:httpclient" }

junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }

# Gradle plugin dependencies
gradlex-java-ecosystem-capabilities = { module = "org.gradlex:java-ecosystem-capabilities"}
