[versions]
javarca = "1.0"
renderer = "1.1"
jamcatch = "1.6"

[libraries]
# Our own modules
javarca-model = { module = "com.example.idiomatic.gradle:javarca-model", version.ref = "javarca" }
javarca-engine = { module = "com.example.idiomatic.gradle:javarca-engine", version.ref = "javarca" }
renderer-lwjgl = { module = "com.example.idiomatic.gradle:renderer-lwjgl", version.ref = "renderer" }
jamcatch-assets = { module = "com.example.idiomatic.gradle:jamcatch-assets", version.ref = "jamcatch" }
jamcatch-actors = { module = "com.example.idiomatic.gradle:jamcatch-actors", version.ref = "jamcatch" }
jamcatch-stage = { module = "com.example.idiomatic.gradle:jamcatch-stage", version.ref = "jamcatch" }

# Logging: SLF4J
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
slf4j-simple = { module = "org.slf4j:slf4j-simple" }
slf4j-jul = {  module = "org.slf4j:slf4j-jdk14" }

# Utilities: Apache Commons
commons-csv = { module = "org.apache.commons:commons-csv", version = "1.14.1" }
commons-io = { module = "commons-io:commons-io", version = "2.21.0" }

# Graphics: LWJGL
lwjgl = { module = "org.lwjgl:lwjgl", version = "3.4.1" }
lwjgl-glfw = { module = "org.lwjgl:lwjgl-glfw" }
lwjgl-opengl = { module = "org.lwjgl:lwjgl-opengl" }
lwjgl-stb = { module = "org.lwjgl:lwjgl-stb" }

# Testing: JUnit
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version = "6.0.3" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
